#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Data configuration for chain matching SOP.
Defines all file paths and data format specifications.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env from project root (silently ignored if file does not exist)
load_dotenv(Path(__file__).parent.parent.parent / ".env")

# Project root: two levels up from this file (chain_matching_sop/config/ -> project root)
PROJECT_ROOT = Path(__file__).parent.parent.parent

# ============================================================================
# Input Data Paths
# ============================================================================

# Chain embeddings: all chain nodes (m_total chains)
CHAIN_EMBEDDINGS_PATH = PROJECT_ROOT / "sample_data" / "chain_embeddings.npz"

# L0 (main industry chain) embedding — stored separately
L0_EMBEDDINGS_PATH = PROJECT_ROOT / "sample_data" / "l0_embedding.npz"

# Chain type classification (A = industry-specific, B = general enabler)
CHAIN_TYPE_CLASSIFICATION_PATH = PROJECT_ROOT / "sample_data" / "chain_type_classification.csv"

# Source embeddings directory and file pattern
# Each file: {ids: (n_batch,), embeddings: (n_batch, d)}
SOURCE_EMBEDDINGS_DIR = PROJECT_ROOT / "sample_data" / "source_embeddings"
SOURCE_EMBEDDINGS_PATTERN = "source_part_*.npz"

# ============================================================================
# Prepared Config Matrices (generated by prepare_chain_config.py)
# ============================================================================

CONFIG_MATRICES_DIR = Path(__file__).parent.parent / "config_matrices"

L0_EMBED_PATH             = CONFIG_MATRICES_DIR / "l0_embed.npz"
SPEC_INDICES_PATH         = CONFIG_MATRICES_DIR / "spec_indices.npy"
OTHER_INDICES_PATH        = CONFIG_MATRICES_DIR / "other_indices.npy"
SPEC_EMBEDS_PATH          = CONFIG_MATRICES_DIR / "spec_embeds.npz"
OTHER_PARENT_EMBEDS_PATH  = CONFIG_MATRICES_DIR / "other_parent_embeds.npz"
EXCLUSION_MAPPING_MATRIX_PATH = CONFIG_MATRICES_DIR / "exclusion_mapping_matrix.npz"
CHAIN_TYPE_VECTOR_PATH    = CONFIG_MATRICES_DIR / "chain_type_vector.npy"
METADATA_PATH             = CONFIG_MATRICES_DIR / "metadata.json"

# ============================================================================
# Threshold Files (generated by calibration pipeline)
# ============================================================================

INPUT_DATA_DIR       = Path(__file__).parent.parent / "input_data"
THRESHOLD_SPEC_PATH  = INPUT_DATA_DIR / "threshold_spec.csv"
THRESHOLD_OTHER_PATH = INPUT_DATA_DIR / "threshold_other.csv"
THRESHOLD_L0_PATH    = INPUT_DATA_DIR / "threshold_l0.json"

# ============================================================================
# Output Paths
# ============================================================================

SIMILARITY_OUTPUT_DIR = Path(__file__).parent.parent / "similarity_output"
MATCHING_OUTPUT_DIR   = Path(__file__).parent.parent / "matching_output"
MATCHING_SUMMARY_PATH = MATCHING_OUTPUT_DIR / "matching_summary.csv"

# ============================================================================
# Calibration — Sampling Configuration
# ============================================================================

# Source data directory: parquet files with original text, used for sampling
SOURCE_DATA_DIR          = PROJECT_ROOT / "sample_data" / "source_texts"
SOURCE_TEXT_FIELD        = "source_text"
SOURCE_DATA_FILE_PATTERN = "source_part_*.parquet"

# Similarity binning parameters
START_SIMILARITY  = 0.4
BIN_WIDTH         = 0.025
SAMPLES_PER_BIN   = 200

SAMPLING_OUTPUT_PATH = None  # defaults to similarity_output/similarity_samples.json

# ============================================================================
# Calibration — LLM Configuration
# ============================================================================

# Read from environment variables; fall back to sensible defaults for local dev.
# LLM_API_URL accepts either a base URL (e.g. https://api.example.com/v1) or a
# full endpoint URL ending in /chat/completions — both forms are normalised below.
_llm_api_base = os.getenv("LLM_API_URL", "http://localhost:8000/v1")
LLM_API_URL = (
    _llm_api_base
    if _llm_api_base.rstrip("/").endswith("/chat/completions")
    else _llm_api_base.rstrip("/") + "/chat/completions"
)
LLM_API_KEY   = os.getenv("LLM_API_KEY",   "sk-xxx")
LLM_MODEL_NAME = os.getenv("LLM_MODEL_NAME", "deepseek-r1")

LLM_RECORDS_PER_BATCH = 8
LLM_MAX_CONCURRENT    = 100
LLM_RETRY_WAIT        = 10
LLM_MAX_RETRIES       = 3
LLM_HTTP_TIMEOUT      = 600
LLM_SAVE_INTERVAL     = 100

LLM_SIMILARITY_SAMPLES_PATH = SIMILARITY_OUTPUT_DIR / "similarity_samples.json"
LLM_CHAIN_DEFINITIONS_PATH  = (
    PROJECT_ROOT / "sample_data" / "chain_definitions.json"
    # For real data: set to the output of parse_chain_definitions.py, e.g.:
    # PROJECT_ROOT / "embedding_code" / "chain_definitions_formatted" / "chain_definitions_{industry}_list.json"
)
LLM_OUTPUT_PATH = SIMILARITY_OUTPUT_DIR / "llm_scope_threshold_results.json"

# ============================================================================
# Calibration — Statistics Generation
# ============================================================================

STATS_INPUT_FILE_PATH   = LLM_OUTPUT_PATH
STATS_OUTPUT_CSV_PATH   = SIMILARITY_OUTPUT_DIR / "chain_matching_statistics.csv"
STATS_OUTPUT_EXCEL_PATH = SIMILARITY_OUTPUT_DIR / "chain_matching_statistics.xlsx"
STATS_MATCH_RESULT_KEY    = "符合"
STATS_MISMATCH_RESULT_KEY = "不符合"
STATS_INTERVAL_WIDTH = 0.025

# ============================================================================
# Calibration — Threshold Generation
# ============================================================================

THRESHOLD_COMPLIANCE_RATE    = 0.7
THRESHOLD_DEFAULT_VALUE      = 100
THRESHOLD_L0_DEFAULT_VALUE   = 0.65
THRESHOLD_CHAIN_NAME_COLUMN  = "产业链环节"
THRESHOLD_COMPLIANCE_RATE_SUFFIX  = "_符合率"
THRESHOLD_SAMPLE_COUNT_SUFFIX     = "_样本数"
THRESHOLD_INPUT_FILE_PATH    = STATS_OUTPUT_EXCEL_PATH
THRESHOLD_OUTPUT_DIR         = INPUT_DATA_DIR

# ============================================================================
# Results Output
# ============================================================================

RESULTS_DIR                 = Path(__file__).parent.parent / "results"
RESULTS_OUTPUT_FILE_NAME    = "final_matching_results.parquet"
RESULTS_SPLIT_INFO_DIR      = SOURCE_DATA_DIR
RESULTS_SOURCE_FILE_PATTERN = SOURCE_DATA_FILE_PATTERN
RESULTS_SOURCE_ID_FIELD     = "id"
RESULTS_SOURCE_CONTENT_FIELDS = ["source_text"]
RESULTS_LOG_LEVEL           = "INFO"

# ============================================================================
# Data Format Constants
# ============================================================================

CHAIN_EMBEDDINGS_KEYS = {
    "chain_names": "chain_names",
    "embeddings":  "embeddings",
}

SOURCE_EMBEDDINGS_KEYS = {
    "ids":        "ids",
    "embeddings": "embeddings",
}

CHAIN_SEPARATOR   = "——"
OTHER_IDENTIFIER  = "其他"
CHAIN_TYPE_A      = "A"
CHAIN_TYPE_B      = "B"
